# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('type', models.CharField(max_length=50)),
                ('effects', models.TextField()),
                ('caracs', models.TextField()),
                ('conds', models.TextField()),
                ('recipe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Consommable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('type', models.CharField(max_length=50)),
                ('effects', models.TextField()),
                ('caracs', models.TextField()),
                ('conds', models.TextField()),
                ('recipe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('type', models.CharField(max_length=50)),
                ('effects', models.TextField()),
                ('caracs', models.TextField()),
                ('conds', models.TextField()),
                ('recipe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=100)),
                ('server', models.CharField(blank=True, max_length=60, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.List')),
            ],
        ),
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('table', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('type', models.CharField(max_length=50)),
                ('effects', models.TextField()),
                ('caracs', models.TextField()),
                ('conds', models.TextField()),
                ('recipe', models.TextField()),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.Objet')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_count', models.IntegerField(default=0)),
                ('server', models.CharField(blank=True, max_length=60, null=True)),
                ('mp', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listitem',
            name='itemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.Objet'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.Objet'),
        ),
        migrations.AddField(
            model_name='consommable',
            name='ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.Objet'),
        ),
        migrations.AddField(
            model_name='arme',
            name='ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.Objet'),
        ),
    ]
