# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arme',
            name='ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lists.Objet'),
        ),
        migrations.AlterField(
            model_name='consommable',
            name='ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lists.Objet'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lists.Objet'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lists.Objet'),
        ),
    ]
