# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objet',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
