# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20160627_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listitem',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listitem',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
