# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 07:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20160601_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='update_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 2, 7, 41, 21, 144000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
