# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20160602_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armes',
            fields=[
                ('ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('type', models.CharField(max_length=50)),
                ('effects', models.TextField()),
                ('caracs', models.TextField()),
                ('conds', models.TextField()),
                ('recipe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Consommables',
            fields=[
                ('ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('type', models.CharField(max_length=50)),
                ('effects', models.TextField()),
                ('caracs', models.TextField()),
                ('conds', models.TextField()),
                ('recipe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipements',
            fields=[
                ('ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('type', models.CharField(max_length=50)),
                ('effects', models.TextField()),
                ('caracs', models.TextField()),
                ('conds', models.TextField()),
                ('recipe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ressources',
            fields=[
                ('ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('type', models.CharField(max_length=50)),
                ('effects', models.TextField()),
                ('caracs', models.TextField()),
                ('conds', models.TextField()),
                ('recipe', models.TextField()),
            ],
        ),
    ]
