# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_armes_consommables_equipements_ressources'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Armes',
            new_name='Arme',
        ),
        migrations.RenameModel(
            old_name='Consommables',
            new_name='Consommable',
        ),
        migrations.RenameModel(
            old_name='Ressources',
            new_name='Equipement',
        ),
        migrations.RenameModel(
            old_name='Equipements',
            new_name='Ressource',
        ),
    ]
