# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20160610_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='server',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
