# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_auto_20160616_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='server',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
